### ISSUE TITLE
"Incorrect value type" error

### ISSUE THREAD

**Issue by amy17519** [seasalt-ai/wiki#333]
@itIsJim  49 wiki pages have "Incorrect value type" error. i took a look and it's due to this `sameAs` param
https://github.com/seasalt-ai/wiki/blob/7fec1b27337cd19644fb942354a2689849137c05/layouts/partials/head/structured-data.html#L33

can you investigate why this parameter only showed up since early Sep?

<img width="1506" alt="Screenshot 2024-10-21 at 14 40 26" src="https://github.com/user-attachments/assets/bf510b5d-d14d-4cb0-869f-06ec1efc4fa1">

**Comment by itIsJim** [comment]
The problem was caused by the fact that the sameAs params was rendered like as [,       "https:\/\/www.linkedin.com\/company\/seasalt-ai\/"], which is an incorrect array format, and thus the error. The fix to the issue in on pr - https://github.com/seasalt-ai/wiki/pull/335. 

To answer the question as to why the error only appeared after the 09/18/2024, we still need to investigate further since the prs that were pulled around that time didnt modify any related files or the html script. 

Here are some significant prs that were pulled at the time:
- wiki search feature: https://github.com/seasalt-ai/wiki/pull/303/files
- crawler issue fix: https://github.com/seasalt-ai/wiki/pull/298/files

Yet, the two prs are not directly related to this issue. 

However, I have a preliminary suspicion: 

The error might be blocked by other pre-existing errors during the compile time. Now the pre-existing has been resolved and thus the program pointer move on to the next error in line. The pre-existing errors can caused by the wiki search feature or crawler issue fix.
